name: Update Stock Index Data

on:
  schedule:
    # 매일 오전 7:00 UTC = 한국시간 오후 4:00 (KST = UTC+9)
    - cron: '0 7 * * 1-5'   # 평일(월~금)만 실행
  workflow_dispatch:          # 수동 실행 버튼도 제공

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 패키지 설치
      - name: Install dependencies
        run: |
          pip install finance-datareader pandas

      # 4. 데이터 업데이트 스크립트 실행
      - name: Run update script
        run: |
          python update_index_data.py

      # 5. 변경된 CSV 파일을 자동 commit & push
      - name: Commit and push updated CSV files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/chapter8/fdr_INDEX_p1d_KS11.csv
          git add data/chapter8/fdr_INDEX_p1d_KQ11.csv
          git add data/chapter8/fdr_INDEX_p1d_US-SnP500.csv
          git add data/chapter8/fdr_INDEX_p1d_QQQ.csv
          # 변경사항이 있을 때만 커밋 (없으면 스킵)
          git diff --staged --quiet || git commit -m "Auto-update index data $(date +'%Y-%m-%d')"
          git push
